parameters:
  num_namenodes: 1
  num_datanodes: 6
  key_name: 'CAP Isuzu'
  image_id: TID-RH7-1NIC.20170807 #CentOS-7 
  admin_user: cloud-user
  flavor_salto: TID-01CPU-01GB-20GB
  flavor_proxy: TID-01CPU-01GB-20GB
  extra_disk_salto: 150
  flavor_nodes: TID-04CPU-16GB-20GB
  extra_disk_namenode: 20
  extra_disk_datanode: 60
  public_net_id: 9b1cc1ab-2648-48b4-bec4-140e41e6f7bb
  public_net2_id: 9b1cc1ab-2648-48b4-bec4-140e41e6f7bb
  private_net_id: 2508c529-42f3-464d-ac22-355cbf3b561d
  private_subnet_id: f6f98460-462b-45ec-9ac0-985b100af526
  ssh_security_group: CAP-sshIn
